name: Raman
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - ipywidgets=7.7.0
  - matplotlib=3.5.1
  - numpy=1.22.3
  - pandas=1.4.1
  - pybaselines=0.8.0
  - python=3.10.4
  - scikit-learn=1.0.2
  - scipy=1.8.0
