name: raman-pca
channels:
  - conda-forge
dependencies:
  - jupyter=1.0.*
  - ipywidgets=7.7.*
  - ipympl=0.8.8
  - matplotlib=3.5.*
  - numpy=1.22.*
  - pandas=1.4.*
  - pybaselines=0.8.*
  - python=3.10.*
  - scikit-learn=1.0.*
  - scipy=1.8.*
  - jupyterlab=3.5.*
  - mlxtend=0.21.*
  - tqdm=4.64.*
  - seaborn=0.12.*
